# Campaign finance data processing

Every election cycle has been different, because the way SOS has reported this data has changed and the types of races and things we've covered have changed. 

This year, I used https://campaignfinance.vermont.gov/public/cf/contribution to download the data and used the Datawrapper API to automatically update the charts for the Election Guide. Note that I have pre-filtered the data to just include statewide races; the full dataset proved too unwieldy.

In [1]:
import pandas as pd
from datawrapper import Datawrapper

/Users/erinpetenko/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
# this is the "password" of sorts for accessing the Datawrapper API to create charts in Python
DATAWRAPPER_ACCESS_TOKEN = "KEY-REDACTED"

### Part 1: Candidate-by-candidate chart

In [3]:
# this is reading the csv into Pandas for further processing. The data automatically downloads with a stupid header line, so I told Pandas to skip a row
df = pd.read_csv("Contributions_10_15_2026.csv", skiprows=1)

In [4]:
# a quick check that it loaded ok.
df.head()

,Entity Id,Committee Name,Candidate First Name,Candidate Last Name,Candidate Middle Name,Contributor Type,Contributor Name,Address Line1,Address Line2,City,State Code,Zip Code,Transaction Date,Transaction Amount,Election Cycle,Filer Type,Contribution Type,Timed Report,Report Name
0,183319,NaN,MOLLY,GRAY,NaN,Individual,"COOKE, RICHARD",37 MAPLE STREET,NaN,BRATTLEBORO,VT,5301,10/12/2026,$50.00,2026,Candidate,Contribution,NaN,2026 Oct 15 - Disclosures
1,301161,NaN,TIM,ASHE,NaN,Individual,"ASHE, CHRISTOPHER",711 N IRVING STREET,NaN,ARLINGTON,VA,22201,10/12/2026,$250.00,2026,Candidate,Contribution,NaN,2026 Oct 15 - Disclosures
2,183319,NaN,MOLLY,GRAY,NaN,Individual,"CASSON, PETER",139 RABBITS RUN,NaN,WILLISTON,VT,5495,10/12/2026,$500.00,2026,Candidate,Contribution,NaN,2026 Oct 15 - Disclosures
3,183319,NaN,MOLLY,GRAY,NaN,Individual,"RIDER, ANNE",2676 TATER LN,NaN,GUILFORD,VT,5301,10/12/2026,$250.00,2026,Candidate,Contribution,NaN,2026 Oct 15 - Disclosures
4,183319,NaN,MOLLY,GRAY,NaN,NaN,Under Threshold - Name Withheld,NaN,NaN,NaN,VT,NaN,10/12/2026,$100.00,2026,Candidate,Contribution,NaN,2026 Oct 15 - Disclosures

In [5]:
df['Contribution Type'].value_counts()

Contribution Type
Contribution    19402
Name: count, dtype: int64

In [6]:
# I noticed the Transaction Amount came with $ symbols which made pandas interpret it as a string. 
# so I removed those symbols and then converted the column into a numeric one.
df['Transaction Amount'] = df['Transaction Amount'].str.replace("$",repl="")
df['Transaction Amount'] = df['Transaction Amount'].str.replace(",",repl="")

df['Transaction Amount'] = pd.to_numeric(df['Transaction Amount'],errors='raise')

In [7]:
# a spare column just so that I could see which candidates were in the data
df['Candidate Full Name'] = df['Candidate First Name'] + " " + df['Candidate Last Name']

In [8]:
df['Candidate Full Name'].unique()

array(['MOLLY GRAY', 'TIM ASHE', 'AMANDA JANOO', 'JOHN RODGERS',
       'PHIL SCOTT', 'LYNN LAFLEUR', 'MIKE PIECIAK',
       'SARAH COPELAND HANZAS', 'CHARITY CLARK', 'BRYAN PONNWITZ',
       'EDWIN KEMON', 'DAVID ZUCKERMAN', 'ALY RICHARDS', 'BRIAN JUDD',
       'CHARLES KRONICK', 'RYAN MCLAREN', 'ZACHARY HAMPL',
       'ESTHER CHARLESTIN', 'JIM CONDOS', 'DANIEL TOWLE',
       'NICHOLAS GRAETER', 'JUNE GOODBAND', 'RACHEL SHAW',
       'THOMAS RENNER'], dtype=object)

In [9]:
#this is a reference spreadsheet with the standardized candidate names, offices, and the candidate ID 
canddict = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSXcK5v0Wrfi7FLkdJFxPx55rLGZPOkThbxOfjmS7QxEgk5JV_O1QSaIQ5g_AnR9q6aTMlng_Olu41R/pub?gid=0&single=true&output=csv",
    index_col="Entity Id")

In [10]:
# now I'm aggregating the data by amount and number of contributions into a pivot table
candpiv = df.pivot_table(index="Entity Id",values=['Transaction Amount'],
               aggfunc="sum").merge(df.pivot_table(index="Entity Id", 
                                                 values='Transaction Date',aggfunc=len),left_index=True,
                                  right_index=True).rename(columns={"Transaction Amount": "Amount raised",
    "Transaction Date":"Number of contributions"}).sort_values(by="Amount raised",ascending=False)

candpiv.head(10)

           Amount raised  Number of contributions
Entity Id
301221         898555.83                     7010
33545          588881.57                     1153
183319         562864.28                     2503
301230         482829.68                     1986
301167         428545.34                     2183
285236         368804.53                      676
242612         257389.38                     2367
301017         179589.50                      486
301161          76938.31                      514
301112          38541.54                      216

In [11]:
# merging the pivot table with the candidate dictionary
candmerge = canddict.merge(candpiv, left_index=True,right_index=True)
candmerge

,Candidate Full Name,VTDigger name,In SOS spreadsheet?,Office,In general?,Amount raised,Number of contributions
Entity Id,,,,,,,
301017,CHARITY CLARK,Charity R. Clark,Yes,Attorney General,Yes,179589.50,486
301161,TIM ASHE,Tim Ashe,Yes,Auditor of Accounts,Yes,76938.31,514
301502,CHARLES KRONICK,Ivar Kronick,Yes,Auditor of Accounts,Yes,6670.00,6
301221,AMANDA JANOO,Amanda Janoo,Yes,Governor,Yes,898555.83,7010
33545,PHIL SCOTT,Phil Scott,Yes,Governor,Yes,588881.57,1153
301494,BRYAN PONNWITZ,Bryan Ponnwitz,No,Governor,Yes,4964.67,17
285236,JOHN RODGERS,John S. Rodgers,Yes,Lieutenant Governor,Yes,368804.53,676
183319,MOLLY GRAY,Molly Gray,Yes,Lieutenant Governor,Yes,562864.28,2503
301332,RACHEL SHAW,Rachel Shaw,Yes,Secretary of State,Yes,100.00,1
242595,SARAH COPELAND HANZAS,Sarah Copeland Hanzas,Yes,Secretary of State,Yes,20499.06,159
242612,MIKE PIECIAK,Mike Pieciak,Yes,State Treasurer,Yes,257389.38,2367
301357,ZACHARY HAMPL,Zachary Hampl,Yes,State Treasurer,Yes,4575.47,10
301382,DANIEL TOWLE,Dan Towle,Yes,Auditor of Accounts,No,7525.00,13
301158,NICHOLAS GRAETER,Nicholas Graeter,Yes,Auditor of Accounts,No,535.00,3
301230,ALY RICHARDS,Aly Richards,Yes,Governor,No,482829.68,1986
301112,ESTHER CHARLESTIN,Esther Charlestin,Yes,Lieutenant Governor,No,38541.54,216
301167,RYAN MCLAREN,Ryan McLaren,Yes,Lieutenant Governor,No,428545.34,2183
227923,DAVID ZUCKERMAN,David Zuckerman,No,NaN,No,1204.79,78
301431,JUNE GOODBAND,June Goodband,No,NaN,No,991.25,6
280600,THOMAS RENNER,Thomas Renner,No,NaN,No,84.00,2
2,JIM CONDOS,Jim Condos,No,NaN,No,0.01,1

In [12]:
# making some tweaks for what it will look like to display it in Datawrapper
canddisplay = candmerge[candmerge['In SOS spreadsheet?'] == "Yes"].rename(columns={"VTDigger name":"Candidate"})[["Candidate", "Office",  "Amount raised","Number of contributions"]]

canddisplay

# canddisplay.to_clipboard()

,Candidate,Office,Amount raised,Number of contributions
Entity Id,,,,
301017,Charity R. Clark,Attorney General,179589.50,486
301161,Tim Ashe,Auditor of Accounts,76938.31,514
301502,Ivar Kronick,Auditor of Accounts,6670.00,6
301221,Amanda Janoo,Governor,898555.83,7010
33545,Phil Scott,Governor,588881.57,1153
285236,John S. Rodgers,Lieutenant Governor,368804.53,676
183319,Molly Gray,Lieutenant Governor,562864.28,2503
301332,Rachel Shaw,Secretary of State,100.00,1
242595,Sarah Copeland Hanzas,Secretary of State,20499.06,159
242612,Mike Pieciak,State Treasurer,257389.38,2367
301357,Zachary Hampl,State Treasurer,4575.47,10
301382,Dan Towle,Auditor of Accounts,7525.00,13
301158,Nicholas Graeter,Auditor of Accounts,535.00,3
301230,Aly Richards,Governor,482829.68,1986
301112,Esther Charlestin,Lieutenant Governor,38541.54,216
301167,Ryan McLaren,Lieutenant Governor,428545.34,2183

In [13]:
dw = Datawrapper(DATAWRAPPER_ACCESS_TOKEN)

#ID for the candidate chart I created
cand_chart = 'dtLeu'

# Updating the data in the chart
dw.add_data(
 cand_chart,
 canddisplay
)

True

### Part 2: Donor Types

In [14]:
#Cleaning donor type data
df['Contributor Type'].value_counts()

Contributor Type
Individual                     7918
Business/Group/Organization     199
Candidate                        25
Self                             24
Political Party                  16
PAC                               9
Name: count, dtype: int64

In [15]:
df['Contributor Type Cleaned'] = df.apply(lambda x: "Total of contributions $100.00 or less" if x['Contributor Name'] == 'Under Threshold - Name Withheld' else x['Contributor Type'], axis=1)

df['Contributor Type Cleaned'].value_counts()

Contributor Type Cleaned
Total of contributions $100.00 or less    11211
Individual                                 7918
Business/Group/Organization                 199
Candidate                                    25
Self                                         24
Political Party                              16
PAC                                           9
Name: count, dtype: int64

In [16]:
catpiv = df.pivot_table(index='Contributor Type Cleaned', values='Transaction Amount', aggfunc='sum').sort_values(by='Transaction Amount', ascending=False)

catpiv

                                        Transaction Amount
Contributor Type Cleaned
Individual                                      3083648.41
Total of contributions $100.00 or less           465863.04
Business/Group/Organization                      267923.76
Political Party                                   61678.80
PAC                                               23890.00
Candidate                                         22473.00
Self                                              16228.34

In [17]:
# creating a pivot table of the cleaned data
catdisplay = catpiv.reset_index().rename(columns={'Contributor Type Cleaned': 'Contributor Type',
                                                  'Transaction Amount':'Amount'})

In [18]:
catdisplay

                         Contributor Type      Amount
0                              Individual  3083648.41
1  Total of contributions $100.00 or less   465863.04
2             Business/Group/Organization   267923.76
3                         Political Party    61678.80
4                                     PAC    23890.00
5                               Candidate    22473.00
6                                    Self    16228.34

In [19]:
#ID for the candidate chart I created
cat_chart = 'udRX9'

# Updating the data in the chart
dw.add_data(
 cat_chart,
 catdisplay
)

True

### Part 3: Historic data comparison

In [20]:

# checking which reports have been submitted so far this election cycle
df['Report Name'].unique()

array(['2026 Oct 15 - Disclosures', '2026 Oct 1 - Disclosures',
       '2026 Sep 1 - Disclosures', '2026 Aug 1 - Disclosures',
       '2026 Jul 1 - Disclosures', '2026 Mar 15 - Disclosures',
       '2025 Jul 1 - Disclosures'], dtype=object)

In [21]:
# Reading in the 2024 data 

df_2024 = pd.read_csv("archived_data/2024_contributions.csv", skiprows=1)

df_2024['Transaction Amount'] = df_2024['Transaction Amount'].str.replace("$",repl="")
df_2024['Transaction Amount'] = df_2024['Transaction Amount'].str.replace(",",repl="")

df_2024['Transaction Amount'] = pd.to_numeric(df_2024['Transaction Amount'],errors='raise')

In [22]:
df_2024.head()

,Entity Id,Committee Name,Candidate First Name,Candidate Last Name,Candidate Middle Name,Contributor Type,Contributor Name,Address Line1,Address Line2,City,State Code,Zip Code,Transaction Date,Transaction Amount,Election Cycle,Filer Type,Contribution Type,Timed Report,Report Name
0,227923,NaN,DAVID,ZUCKERMAN,NaN,Political Party,VERMONT PROGRESSIVE PARTY,PO BOX 281,NaN,MONTPELIER,VT,05601,12/12/2024,5857.47,2024,Candidate,Contribution,NaN,12/15/2024 - GENERAL
1,285236,NaN,JOHN,RODGERS,NaN,Individual,"POMERLEAU, ERNEST",69 COLLEGE STREET,NaN,BURLINGTON,VT,05401,12/12/2024,2000.00,2024,Candidate,Contribution,NaN,12/15/2024 - GENERAL
2,242612,NaN,MIKE,PIECIAK,NaN,Individual,"D'ALESSANDRO, MAC",333 BRUSH HILL RD,UNIT Z3,MILTON,MA,02186-1243,12/12/2024,250.00,2024,Candidate,Contribution,NaN,12/15/2024 - GENERAL
3,227923,NaN,DAVID,ZUCKERMAN,NaN,NaN,Under Threshold - Name Withheld,NaN,NaN,NaN,NaN,NaN,12/11/2024,10.00,2024,Candidate,Contribution,NaN,12/15/2024 - GENERAL
4,227923,NaN,DAVID,ZUCKERMAN,NaN,Individual,"ANDREWS, CATHARINE H.",235 PARK ST,#1,BURLINGTON,VT,05401,12/11/2024,15.00,2024,Candidate,Contribution,NaN,12/15/2024 - GENERAL

In [23]:

# checking which reports are in the 2024 data
df_2024['Report Name'].unique()

array(['12/15/2024 - GENERAL', '11/19/2024 - GENERAL',
       '11/01/2024 - GENERAL', '10/15/2024 - GENERAL',
       '10/01/2024 - GENERAL', '09/01/2024 - GENERAL',
       '08/01/2024 - GENERAL', '07/01/2024 - GENERAL',
       '03/15/2024 - GENERAL', '07/01/2023 - GENERAL'], dtype=object)

In [24]:
# filtering down to just the 2024 reports that match up with the 2026 ones. This isn't always perfect, because the dates 
# have occasionally changed over the years, but I do my best.

reports_to_keep = ['07/01/2024 - GENERAL', 
       '03/15/2024 - GENERAL', '07/01/2023 - GENERAL', '08/01/2024 - GENERAL',
                '09/01/2024 - GENERAL' , '10/15/2024 - GENERAL',
       '10/01/2024 - GENERAL']

df_2024_filtered = df_2024[df_2024['Report Name'].isin(reports_to_keep)]

In [25]:
# checking that the numbers coming out make sense & formatting them correctly

print('${:,.0f}'.format(df['Transaction Amount'].sum()))
print('${:,.0f}'.format(df_2024_filtered['Transaction Amount'].sum()))

$3,941,705
$1,260,278

In [26]:
comp_chart = 'Vmtpi'

# Updating the data in the chart
dw.update_description(
 chart_id = comp_chart,
 intro = "<b>" + '${:,.0f}'.format(df['Transaction Amount'].sum()) + "</b> has been raised so far by statewide candidates in the 2026 election cycle.<br><br>That's compared to <b>" + '${:,.0f}'.format(df_2024_filtered['Transaction Amount'].sum()) + "</b> raised at about this point in the 2024 cycle.<br><br><b>Statewide candidate contributions for previous years:</b>"
)

{'publicId': 'Vmtpi',
 'language': 'en-US',
 'theme': 'datawrapper',
 'id': 'Vmtpi',
 'type': 'column-chart',
 'title': 'Contributions by year 2026',
 'lastEditStep': 5,
 'publishedAt': '2026-07-27T20:46:18.000Z',
 'publicUrl': 'https://datawrapper.dwcdn.net/Vmtpi/6/',
 'publicVersion': 6,
 'deleted': False,
 'forkable': False,
 'isFork': False,
 'metadata': {'data': {'changes': [],
   'transpose': False,
   'vertical-header': True,
   'horizontal-header': True,
   'column-format': {'Total with inflation': {'type': 'auto',
     'ignore': False,
     'number-append': '',
     'number-format': 'auto',
     'number-divisor': 0,
     'number-prepend': '$'}},
   'upload-method': 'copy'},
  'describe': {'source-name': 'Vermont Secretary of State',
   'source-url': 'https://campaignfinance.vermont.gov/Public/ReceiptsList',
   'intro': "<b>$3,941,705</b> has been raised so far by statewide candidates in the 2026 election cycle.<br><br>That's compared to <b>$1,260,278</b> raised at about this point in the 2024 cycle.<br><br><b>Statewide candidate contributions for previous years:</b>",
   'byline': 'Erin Petenko',
   'aria-description': 'A bar chart of contributions by election cycle. Contributions were highest in 2016, then dropped in 2018, but slowly rose in 2020 and 2022. You can download this data to read it in a screenreader-friendly format. ',
   'number-format': '-',
   'number-divisor': 0,
   'number-append': '',
   'number-prepend': '',
   'hide-title': True},
  'visualize': {'dark-mode-invert': True,
   'highlighted-series': [],
   'highlighted-values': [],
   'sharing': {'enabled': False,
    'url': 'https://www.datawrapper.de/_/Vmtpi',
    'auto': False},
   'lines': {'Total with inflation': {'title': 'Total contribution amounts by election cycle',
     'colorKey': True,
     'directLabel': False}},
   'x-grid': 'off',
   'y-grid': 'on',
   'compare': {'enabled': False, 'differenceLabel': True},
   'scale-y': 'linear',
   'sort-by': 'first',
   'category': 'direct',
   'overlays': [],
   'color-key': True,
   'base-color': '#0028b3',
   'grid-lines': 'show',
   'bar-padding': 60,
   'label-space': 30,
   'sort-values': False,
   'valueLabels': {'show': 'hover',
    'enabled': True,
    'placement': 'outside',
    'preventOverlap': True},
   'yAxisLabels': {'enabled': True,
    'alignment': 'left',
    'placement': 'outside'},
   'custom-range': ['', '15000000'],
   'custom-ticks': '',
   'disable-tabs': True,
   'grid-lines-x': {'type': 'ticks', 'enabled': False},
   'label-colors': False,
   'label-margin': 0,
   'stack-to-100': False,
   'totalsLabels': False,
   'interpolation': 'linear',
   'negativeColor': {'value': '#E31A1C', 'enabled': False},
   'reverse-order': False,
   'rotate-labels': 'auto',
   'show-tooltips': True,
   'x-grid-format': 'YYYY',
   'y-grid-format': 'auto',
   'y-grid-labels': 'auto',
   'absolute-scale': False,
   'categoryLabels': {'enabled': True, 'position': 'direct'},
   'chart-type-set': True,
   'color-category': {'map': {},
    'palette': [],
    'categoryOrder': [],
    'categoryLabels': {},
    'excludeFromKey': []},
   'custom-range-x': ['', ''],
   'custom-range-y': ['', '15000000'],
   'custom-ticks-x': '2016,2018,2020,2022,2024',
   'custom-ticks-y': '',
   'plotHeightMode': 'fixed',
   'series-padding': 60,
   'show-color-key': True,
   'xGridAlignment': 'baseline',
   'color-by-column': True,
   'connector-lines': True,
   'plotHeightFixed': 300,
   'plotHeightRatio': 0.5,
   'text-annotations': [],
   'y-grid-subdivide': True,
   'custom-area-fills': [],
   'range-annotations': [],
   'stack-color-legend': False,
   'y-grid-label-align': 'left'},
  'axes': {'column': 'Total with inflation'},
  'publish': {'embed-width': 600,
   'embed-height': 491,
   'blocks': {'logo': {'enabled': False},
    'embed': False,
    'download-pdf': False,
    'download-svg': False,
    'get-the-data': True,
    'download-image': False},
   'export-pdf': {},
   'embed-codes': {'embed-method-iframe': '<iframe title="Contributions by year 2026" aria-label="Column Chart" id="datawrapper-chart-Vmtpi" src="https://datawrapper.dwcdn.net/Vmtpi/6/" scrolling="no" frameborder="0" style="border: none;" width="600" height="491" data-external="1"></iframe>',
    'embed-method-responsive': '<iframe title="Contributions by year 2026" aria-label="Column Chart" id="datawrapper-chart-Vmtpi" src="https://datawrapper.dwcdn.net/Vmtpi/6/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="491" data-external="1"></iframe><script type="text/javascript">(function(){function e(){window.addEventListener(`message`,function(e){if(e.data[`datawrapper-height`]!==void 0){var t=document.querySelectorAll(`iframe`);for(var n in e.data[`datawrapper-height`])for(var r=0,i;i=t[r];r++)if(i.contentWindow===e.source){var a=e.data[`datawrapper-height`][n]+`px`;i.style.height=a}}})}e()})();</script>',
    'embed-method-web-component': '<div style="min-height:491px" id="datawrapper-vis-Vmtpi"><script type="text/javascript" defer src="https://datawrapper.dwcdn.net/Vmtpi/embed.js" charset="utf-8" data-target="#datawrapper-vis-Vmtpi"></script><noscript><img src="https://datawrapper.dwcdn.net/Vmtpi/full.png" alt="A bar chart of contributions by election cycle. Contributions were highest in 2016, then dropped in 2018, but slowly rose in 2020 and 2022. You can download this data to read it in a screenreader-friendly format." /></noscript></div>'},
   'autoDarkMode': False,
   'chart-height': 330},
  'annotate': {'notes': 'Inflation-adjusted to 2026 dollars. Includes all money raised from November of the previous year to the day of the general election.'},
  'custom': {}},
 'externalData': None,
 'utf8': False,
 'createdAt': '2026-07-23T14:11:02.000Z',
 'lastModifiedAt': '2026-10-26T14:26:52.000Z',
 'forkedFrom': 'JrbBq',
 'organizationId': 'uTOqi4_5',
 'authorId': 167415,
 'workspace': 'vtdigger',
 'folderId': 426094,
 'deletedAt': None,
 'url': '/v3/charts/Vmtpi'}